import argparse
from pathlib import Path
import sys
from cif_to_lmp import cif_to_lmp
from cif_to_xyz import cif_to_xyz
from lammpstrj_to_modified_xyz import lammpstrj_to_modified_xyz
from lammpstrj_to_xyz import lammpstrj_to_xyz
from lmp_to_cif import lmp_to_cif
from lmp_to_modified_xyz import lmp_to_modified_xyz
from lmp_to_xyz import lmp_to_xyz
from xyz_to_cif import xyz_to_cif
from xyz_to_lmp import xyz_to_lmp
from split_trajectory import split_trajectory
from xyz_to_vasp import convert_xyz_to_vasp
from vasp_to_xyz import convert_vasp_to_xyz
from batch_convert import batch_convert
from lmpstep_to_xyz import lmpstep_to_xyz 

EXTENSIONS = {
    "cif": ".cif",
    "lmp": ".lmp",
    "xyz": ".xyz",
    "lammpstrj": ".lammpstrj",
    "vasp": ".vasp",
    "POSCAR": ".vasp",
    "lmpstep": ".lmpstep"
}

VERSION = "1.0.0"
AUTHOR = "Rielly Castle"
DESCRIPTION = "A structure file converter"

def print_banner():
    banner_path = Path(__file__).with_name("banner.txt")

    try:
        with open(banner_path, "r", encoding="utf-8") as f:
            print(f.read())
    except FileNotFoundError:
        print("FFMCHEM")

    print(DESCRIPTION)
    print(f"Version : {VERSION}")
    print(f"Author  : {AUTHOR}")
    print()

def parse_atom_map(map_args):
    if map_args is None:
        return {}, {}

    type_map = {}
    symbol_map = {}

    for item in map_args:
        atom_type, symbol = item.split(":")
        atom_type = int(atom_type)
        type_map[atom_type] = symbol
        symbol_map[symbol] = atom_type
    return type_map, symbol_map

def parse_mass_map(mass_args):
    if mass_args is None:
        return {}

    mass_map = {}

    for item in mass_args:
        atom_type, mass = item.split(":")
        mass_map[int(atom_type)] = float(mass)

    return mass_map

def split_xyz_by_atom_type(xyz_file, output_dir, output_name=None):
    xyz_file = Path(xyz_file)
    output_dir = Path(output_dir)

    if output_name is None:
        output_name = xyz_file.name

    with open(xyz_file, "r") as infile:
        lines = infile.readlines()

    frames = []
    i = 0
    while i < len(lines):
        if not lines[i].strip():
            i += 1
            continue

        n_atoms = int(lines[i].strip())
        comment = lines[i + 1]
        atom_lines = lines[i + 2:i + 2 + n_atoms]

        frames.append((comment, atom_lines))
        i += 2 + n_atoms

    atom_types = sorted(set(line.split()[0] for _, atom_lines in frames for line in atom_lines))

    for atom_type in atom_types:
        atom_dir = output_dir / f"atom_{atom_type}"
        atom_dir.mkdir(parents=True, exist_ok=True)
        atom_output_file = atom_dir / output_name

        with open(atom_output_file, "w") as outfile:
            for comment, atom_lines in frames:
                selected_atoms = [line for line in atom_lines if line.split()[0] == atom_type]
                outfile.write(f"{len(selected_atoms)}\n")
                outfile.write(comment)
                for line in selected_atoms:
                    outfile.write(line)

def run_single_conversion(args, input_file, output_file):
    input_file = Path(input_file)
    output_file = Path(output_file)
    type_map, symbol_map = parse_atom_map(args.map)
    mass_map = parse_mass_map(args.mass_map)

    if args.input_format == "cif" and args.output_format == "lmp":
        cif_to_lmp(input_file, output_file, symbol_map=symbol_map, mass_map=mass_map)

    elif args.input_format == "lmp" and args.output_format == "cif":
        lmp_to_cif(input_file,output_file,type_map=type_map,lattice_type=args.lattice_type,space_group=args.space_group)

    elif args.input_format == "lmp" and args.output_format == "xyz":
        if args.modified:
            lmp_to_modified_xyz(input_file, output_file)
        else:
            lmp_to_xyz(input_file, output_file, type_map=type_map)

    elif args.input_format == "xyz" and args.output_format == "lmp":
        xyz_to_lmp(input_file, output_file, symbol_map=symbol_map, mass_map=mass_map)

    elif args.input_format == "xyz" and args.output_format == "cif":
        xyz_to_cif(input_file,output_file,lattice_type=args.lattice_type, space_group=args.space_group)

    elif args.input_format == "cif" and args.output_format == "xyz":
        cif_to_xyz(input_file, output_file)

    elif args.input_format == "xyz" and args.output_format == "vasp":
        convert_xyz_to_vasp(input_file, output_file, comment="Generated by Ffmchem XYZ to VASP converter")

    elif args.input_format == "xyz" and args.output_format == "vasp":
        convert_vasp_to_xyz(input_file, output_file)

    elif args.input_format == "lammpstrj" and args.output_format == "xyz":
        if args.modified:
            lammpstrj_to_modified_xyz(input_file,output_file,coordinate_mode=args.coordinates)
        else:
            lammpstrj_to_xyz(input_file,output_file,type_map=type_map,coordinate_mode=args.coordinates)

    else:
        raise ValueError(f"Unsupported conversion: {args.input_format} to {args.output_format}")

def run_atom_centric_conversion(args, input_file, output_target):
    input_file = Path(input_file)
    output_target = Path(output_target)

    if args.output_format != "xyz":
        raise ValueError("--atom-centric currently only supports XYZ output.")

    if output_target.suffix:
        output_dir = output_target.parent
        output_name = output_target.name
    else:
        output_dir = output_target
        output_name = input_file.with_suffix(".xyz").name

    output_dir.mkdir(parents=True, exist_ok=True)
    temp_file = output_dir / f"__tmp_{output_name}"
    run_single_conversion(args, input_file, temp_file)
    split_xyz_by_atom_type(temp_file, output_dir, output_name=output_name)
    temp_file.unlink()

def run_batch_conversion(args):
    input_dir = Path(args.input)
    output_dir = Path(args.output)
    
    if not input_dir.exists():
        raise ValueError(f"Input directory {input_dir} does not exist")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    type_map, symbol_map = parse_atom_map(args.map)
    mass_map = parse_mass_map(args.mass_map)
    
    # Define wrapper for lmpstep conversion
    def lmpstep_wrapper(input_file, output_file):
        lmpstep_to_xyz(input_file, output_file, type_map=type_map, coordinate_mode=args.coordinates)
    
    # Define wrapper for lmp conversion
    def lmp_wrapper(input_file, output_file):
        if args.modified:
            lmp_to_modified_xyz(input_file, output_file)
        else:
            lmp_to_xyz(input_file, output_file, type_map=type_map)
    
    # Define wrapper for lammpstrj conversion
    def lammpstrj_wrapper(input_file, output_file):
        if args.modified:
            lammpstrj_to_modified_xyz(input_file, output_file, coordinate_mode=args.coordinates)
        else:
            lammpstrj_to_xyz(input_file, output_file, type_map=type_map, coordinate_mode=args.coordinates)
    
    # Define wrapper for xyz to cif conversion
    def xyz_to_cif_wrapper(input_file, output_file):
        xyz_to_cif(input_file, output_file, lattice_type=args.lattice_type, space_group=args.space_group)
    
    # Define wrapper for lmp to cif conversion
    def lmp_to_cif_wrapper(input_file, output_file):
        lmp_to_cif(input_file, output_file, type_map=type_map, lattice_type=args.lattice_type, space_group=args.space_group)
    
    # Define wrapper for cif to lmp conversion
    def cif_to_lmp_wrapper(input_file, output_file):
        cif_to_lmp(input_file, output_file, symbol_map=symbol_map, mass_map=mass_map)
    
    # Define wrapper for xyz to lmp conversion
    def xyz_to_lmp_wrapper(input_file, output_file):
        xyz_to_lmp(input_file, output_file, symbol_map=symbol_map, mass_map=mass_map)
    
    # Define wrapper for xyz to vasp conversion
    def xyz_to_vasp_wrapper(input_file, output_file):
        convert_xyz_to_vasp(input_file, output_file, comment=args.title)
    
    converters = {
        ("cif", "lmp"): (cif_to_lmp_wrapper, ".cif", ".lmp"),
        ("cif", "xyz"): (cif_to_xyz, ".cif", ".xyz"),
        ("lmp", "cif"): (lmp_to_cif_wrapper, ".lmp", ".cif"),
        ("lmp", "xyz"): (lmp_wrapper, ".lmp", ".xyz"),
        ("lmpstep", "xyz"): (lmpstep_wrapper, ".lmp", ".xyz"),
        ("lammpstrj", "xyz"): (lammpstrj_wrapper, ".lammpstrj", ".xyz"),
        ("xyz", "cif"): (xyz_to_cif_wrapper, ".xyz", ".cif"),
        ("xyz", "lmp"): (xyz_to_lmp_wrapper, ".xyz", ".lmp"),
        ("xyz", "vasp"): (xyz_to_vasp_wrapper, ".xyz", ".vasp"),
        ("vasp", "xyz"): (convert_vasp_to_xyz, ".vasp", ".xyz"),
    }
    
    key = (args.input_format, args.output_format)
    if key not in converters:
        raise ValueError(f"Batch conversion not supported for {args.input_format} -> {args.output_format}")
    
    converter_func, input_ext, output_ext = converters[key]
    
    if args.atom_centric:
        if args.output_format != "xyz":
            raise ValueError("--atom-centric currently only supports XYZ output.")
        input_files = sorted(input_dir.glob(f"*{input_ext}"))
        if not input_files:
            print(f"No {input_ext} files found in {input_dir}")
            return
        for input_file in input_files:
            output_file = output_dir / input_file.with_suffix(".xyz").name
            run_atom_centric_conversion(args, input_file, output_file)
    else:
        batch_convert(input_folder=str(input_dir),output_folder=str(output_dir),converter_func=converter_func,input_ext=input_ext, output_ext=output_ext)


def main():
    parser = argparse.ArgumentParser(description="Ffmchem: Command-line tool for converting between common atomistic structure file formats.")

    parser.add_argument("--input",required=True,help="Input file for single conversion, or input directory when using --batch.")
    parser.add_argument("--output",required=True,help="Output file for single conversion, or output directory when using --batch.")
    parser.add_argument("--from",dest="input_format",required=True,choices=["cif", "lmp", "xyz", "vasp", "lammpstrj", "lmpstep"],help="Input file format.")
    parser.add_argument("--to",dest="output_format", choices=["cif", "lmp", "xyz", "vasp"],help="Output file format.")
    parser.add_argument("--map",nargs="+",default=None,help="Atom type mapping. Example: --map 1:O 2:H")
    parser.add_argument("--mass-map",nargs="+",default=None,help="Atomic masses for LAMMPS data files. Example: --mass-map 1:15.999 2:1.008")
    parser.add_argument("--batch",action="store_true",help="Convert every matching file in the input directory.")
    parser.add_argument("--modified",action="store_true",help="Use the modified XYZ format (numeric atom types).")
    parser.add_argument("--atom-centric", action="store_true", help="Produce one output file for each atom type. Output files are placed into atom-specific folders.")
    parser.add_argument("--coordinates", choices=["auto", "scaled", "unscaled"], default="auto", help="Coordinate convention used in LAMMPS trajectory files. 'auto' detects the format automatically.")
    parser.add_argument("--lattice-type",default="triclinic",help="CIF lattice type written to _symmetry_cell_setting (default: orthorhombic).")
    parser.add_argument("--space-group",default="P 1",help="CIF space group written to _symmetry_space_group_name_H-M (default: 'P 1').")
    parser.add_argument("--title",default="Generated by Ffmchem",help="Title written to the first line of GRO files.")
    parser.add_argument("--split",action="store_true",help="Split an XYZ or LAMMPS trajectory into individual timestep files.")

    if len(sys.argv) == 1:
        print_banner()
        parser.print_help()
        return

    args = parser.parse_args()

    if not args.split and args.output_format is None:
        parser.error("--to is required unless using --split.")

    if args.split:
        split_trajectory(args.input,args.output,args.input_format)
        return

    if args.atom_centric and args.output_format != "xyz":
        raise ValueError("--atom-centric currently only supports XYZ output.")

    if args.batch:
        run_batch_conversion(args)
    else:
        if args.atom_centric:
            run_atom_centric_conversion(args,Path(args.input),Path(args.output))
        else:
            run_single_conversion(args,Path(args.input),Path(args.output))

if __name__ == "__main__":
    main()
