import numpy as np
from collections import Counter
import os

def parse_xyz_cell_parameters(comment_line):

    parts = comment_line.strip().split()
    
    if len(parts) < 6:
        raise ValueError(f"Comment line must contain 6 cell parameters (a b c xy xz yz). Got: {comment_line}")
    
    try:
        a, b, c, xy, xz, yz = map(float, parts[:6])
        return a, b, c, xy, xz, yz
    except ValueError as e:
        raise ValueError(f"Error parsing cell parameters: {e}. Comment line: {comment_line}")

def construct_lattice_vectors(a, b, c, xy, xz, yz):
    v1 = np.array([a, 0.0, 0.0])
    v2 = np.array([xy, b, 0.0])
    v3 = np.array([xz, yz, c])
    return np.array([v1, v2, v3])

def count_atom_types(atom_data):
    elements = [atom[0] for atom in atom_data]
    return Counter(elements)

def parse_xyz_data(lines):
    if len(lines) < 3:
        raise ValueError("XYZ file is too short or malformed.")
    
    # First line: number of atoms
    try:
        num_atoms = int(lines[0].strip())
    except ValueError:
        raise ValueError(f"Invalid number of atoms on first line: {lines[0]}")
    
    # Second line: comment line with cell parameters
    comment_line = lines[1].strip()
    a, b, c, xy, xz, yz = parse_xyz_cell_parameters(comment_line)
    cell_params = (a, b, c, xy, xz, yz)
    
    # Parse atom data
    atom_data = []
    for line in lines[2:2+num_atoms]:
        parts = line.strip().split()
        if len(parts) < 4:
            continue
        try:
            element = parts[0]
            x, y, z = map(float, parts[1:4])
            atom_data.append((element, x, y, z))
        except ValueError:
            pass
    
    if len(atom_data) != num_atoms:
        pass
    
    return num_atoms, cell_params, atom_data

def write_vasp_poscar(filename, atom_data, cell_params, comment="Generated by Ffmchem XYZ to VASP converter"):
    a, b, c, xy, xz, yz = cell_params
    lattice_vectors = construct_lattice_vectors(a, b, c, xy, xz, yz)
    
    # Count atom types
    atom_counts = count_atom_types(atom_data)
    atom_types = sorted(atom_counts.keys())
    atom_counts_list = [atom_counts[atom] for atom in atom_types]
    
    with open(filename, 'w') as f:
        # Write header
        f.write(f"{comment}\n")
        f.write("1.0\n")  # Scaling factor
        
        # Write lattice vectors
        f.write(f"{lattice_vectors[0][0]:.12f} {lattice_vectors[0][1]:.12f} {lattice_vectors[0][2]:.12f}\n")
        f.write(f"{lattice_vectors[1][0]:.12f} {lattice_vectors[1][1]:.12f} {lattice_vectors[1][2]:.12f}\n")
        f.write(f"{lattice_vectors[2][0]:.12f} {lattice_vectors[2][1]:.12f} {lattice_vectors[2][2]:.12f}\n")
        
        # Write atom types
        f.write("  " + " ".join(atom_types) + "\n")
        
        # Write atom counts
        f.write("  " + " ".join(map(str, atom_counts_list)) + "\n")
        
        # Write coordinate system (Cartesian)
        f.write("Cartesian\n")
        
        # Write coordinates (keep as Cartesian, no conversion)
        for element, x, y, z in atom_data:
            f.write(f"{x:.12f} {y:.12f} {z:.12f}\n")

def convert_xyz_to_vasp(input_file, output_file, comment="Generated by Ffmchem XYZ to VASP converter"):
    if not os.path.exists(input_file):
        raise FileNotFoundError(f"Input file {input_file} does not exist")
    
    # Determine output file name if not provided
    if output_file is None:
        if input_file.endswith('.xyz'):
            output_file = input_file[:-4] + '.vasp'
        else:
            output_file = input_file + '.vasp'
    
    # Read input file
    with open(input_file, 'r') as f:
        lines = f.readlines()
    
    # Parse XYZ data
    num_atoms, cell_params, atom_data = parse_xyz_data(lines)
    
    # Write POSCAR file
    write_vasp_poscar(output_file, atom_data, cell_params, comment)
